### ISSUE TITLE
Fix the issue of Maps

### ISSUE THREAD

**Issue by AlishahMughal123** [BrianRuizy/covid-19-dashboard#2]
There`s a problem on  **/maps.html** It`s not loading and giving this error 

![image](https://user-images.githubusercontent.com/52525188/77747846-25590e80-7041-11ea-8bc1-499ad2892283.png)

![image](https://user-images.githubusercontent.com/52525188/77747796-107c7b00-7041-11ea-9d42-29b04bd60af2.png)

Thanks

**Comment by BrianRuizy** [comment]
At the moment there is no _map style_ plots implementation. This issue should rather be **Add map plots** *. And, labeled accordingly I.e.: Feature.

**Comment by AlishahMughal123** [comment]
Okay Cool 👍
