### ISSUE TITLE
make trend's arrow-icons dynamic based on value

### ISSUE THREAD

**Issue by BrianRuizy** [BrianRuizy/covid-19-dashboard#21]
![Screen Shot 2020-05-05 at 1 48 12 AM](https://user-images.githubusercontent.com/23439187/81041141-a68e9700-8e72-11ea-8be5-0205a00a8c6e.png)

With Django [filters/tags](https://docs.djangoproject.com/en/3.0/ref/templates/builtins/) dynamically display the css arrow icon, respective to the value. 
Use following logic for the trends:
| variable         | value | color | arrow      |
|------------------|:-----:|-------|------------|
| death_rate_trend |   -   | green | arrow-down |
| recovered_trend  |   +   | green | arrow-up   |
| confirmed_trend  |   +   | red   | arrow-up   |
| deaths_trend     |   +   | red   | arrow-up   |

**Comment by mateuszz0000** [comment]
I will work on it :guitar:

**Comment by BrianRuizy** [comment]
#24
