### ISSUE TITLE
Exception Value: single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by mateuszz0000** [BrianRuizy/covid-19-dashboard#22]
Hello. I've got following error when I try to runserver first time:
```
IndexError at /
single positional indexer is out-of-bounds
```
 I tried some debug and I have no data when I put weekly or monthly ==  True. Without param works fine. Should I configure something more before first runserver?

Function which generates error:
```
def percentage_trends():
    """[summary]: Returns percantage of trend, relative to week prior delta
    Returns:
        [dataframe] -- [percentage objects]
    """    
    current = realtime_growth(weekly=True).iloc[-1]
    last_week = realtime_growth(weekly=True).iloc[-2]
    trends = round(number=((current - last_week)/last_week)*100, ndigits=1)
    
    rate_change = round(((current.Deaths/current.Confirmed)*100)-((last_week.Deaths / last_week.Confirmed)*100), ndigits=2)
    trends = trends.append(pd.Series(data=rate_change, index=['Death_rate']))
    
    return trends
```

**Comment by BrianRuizy** [comment]
@mateuszz0000 What python version are you running?

**Comment by mateuszz0000** [comment]
3.8.2

**Comment by BrianRuizy** [comment]
What operating system? Also, any errors installing the dependencies? 
Another user, also had the same issue running on Python 3.8.2 -> #6

**Comment by mateuszz0000** [comment]
Found problem already. I will make PR for a moment :)

**Comment by BrianRuizy** [comment]
@mateuszz0000 Great! I'll be looking out for it.

**Comment by BrianRuizy** [comment]
@mateuszz0000 May you confirm the closing of this issue? and, #6 equally
