### ISSUE TITLE
CI not working

### ISSUE THREAD

**Issue by mateuszz0000** [BrianRuizy/covid-19-dashboard#32]
Need to modify travis.yml to run django tests instead of pytest.

**Comment by BrianRuizy** [comment]
I'm aware of this, I was setting up **continuous delivery** with Heroku first. Now, new pull requests automatically create a new Heroku Review app, and makes for an awesome way to test before merging PR's.  

For instance, PR #31:
![Screen Shot 2020-05-12 at 12 12 38 AM](https://user-images.githubusercontent.com/23439187/81641318-55d4ec00-93e6-11ea-8e40-fa2067356912.png)

Now, I'm going to work on the **CI** with Travis.

**Comment by BrianRuizy** [comment]
#33
